backend:
  name: git-gateway
  branch: main

# Production: remove local_backend for deployment
# local_backend: true

site_url: https://dabanamoh.github.io/dabana-portfolio
display_url: https://dabanamoh.github.io/dabana-portfolio

media_folder: "images/uploads"
public_folder: "/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "case_studies"
    label: "Case Studies"
    folder: "content/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Team Size", name: "teamSize", widget: "string"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Stats"
        name: "stats"
        widget: "list"
        fields:
          - {label: "Number", name: "number", widget: "string"}
          - {label: "Label", name: "label", widget: "string"}
      - {label: "Overview", name: "overview", widget: "markdown"}
      - {label: "Challenge", name: "challenge", widget: "markdown"}
      - {label: "Solution", name: "solution", widget: "markdown"}
      - {label: "Results", name: "results", widget: "markdown"}
      - label: "Timeline"
        name: "timeline"
        widget: "list"
        fields:
          - {label: "Date", name: "date", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
      - label: "Technologies"
        name: "technologies"
        widget: "list"
        fields:
          - {label: "Icon", name: "icon", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - {label: "Image URL", name: "url", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
      - label: "Impact Stats"
        name: "impactStats"
        widget: "list"
        fields:
          - {label: "Number", name: "number", widget: "string"}
          - {label: "Label", name: "label", widget: "string"}
      - label: "Testimonial"
        name: "testimonial"
        widget: "object"
        required: false
        fields:
          - {label: "Quote", name: "quote", widget: "text"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Role", name: "role", widget: "string"}